In [74]:
#Library Import
import numpy as np
import pandas as pd

a. Misising data could be anything in {NA,n/a,"",-1,...}. Read the data and assign the missing data in the dataframe as NaN. Hint: df.replace(...,np.nan,inplace=True)

In [128]:
df = pd.read_csv('Lab1_dataset.csv')
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2003,2003,2,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,"""""",Veenker,1Fam,1Story,6.0,8.0,1976,1976,2,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2001,2002,2,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Crawfor,1Fam,2Story,7.0,NaN,1915,1970,3,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,NoRidge,1Fam,2Story,8.0,5.0,-1,2000,3,250000
5,6,50,RL,85.0,-1,Pave,NaN,IR1,Lvl,AllPub,Inside,Mitchel,1Fam,1.5Fin,5.0,5.0,1993,1995,2,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,Somerst,1Fam,1Story,8.0,5.0,2004,2005,2,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,"""""",NWAmes,1Fam,2Story,7.0,6.0,1973,1973,2,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,OldTown,1Fam,1.5Fin,NaN,5.0,1931,1950,2,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,BrkSide,2fmCon,NaN,5.0,6.0,1939,1950,1,118000

In [143]:
df.replace(["NA", "n/a", "", -1], np.nan, inplace=True)
print(df.head(10))

           Id  Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley  \
SalePrice
208500      0   1          60       RL         65.0   8450.0   Pave  Grvl
181500      1   2          20       RL         80.0   9600.0   Pave  Grvl
223500      2   3          60       RL         68.0  11250.0   Pave  Grvl
140000      3   4          70       RL         60.0   9550.0   Pave  Grvl
143000      5   6          50       RL         85.0   9268.5   Pave  Grvl
307000      6   7          20       RL         75.0  10084.0   Pave  Grvl
200000      7   8          60       RL         69.0  10382.0   Pave  Grvl
129900      8   9          50       RM         51.0   6120.0   Pave  Grvl
118000      9  10         190       RL         50.0   7420.0   Pave  Grvl
345000     11  12          60       RL         85.0  11924.0   Pave  Grvl

          LotShape LandContour  ... LotConfig Neighborhood BldgType  \
SalePrice                       ...
208500         Reg         Lvl  ...    Inside      CollgCr     1Fam
181500         Reg         Lvl  ...        ""      Veenker     1Fam
223500         IR1         Lvl  ...    Inside      CollgCr     1Fam
140000         IR1         Lvl  ...    Corner      Crawfor     1Fam
143000         IR1         Lvl  ...    Inside      Mitchel     1Fam
307000         Reg         Lvl  ...    Inside      Somerst     1Fam
200000         IR1         Lvl  ...        ""       NWAmes     1Fam
129900         Reg         Lvl  ...    Inside      OldTown     1Fam
118000         Reg         Lvl  ...    Corner      BrkSide   2fmCon
345000         IR1         Lvl  ...    Inside      NridgHt     1Fam

          HouseStyle OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
SalePrice
208500        2Story         7.0          5.0     2003.0          2003
181500        1Story         6.0          8.0     1976.0          1976
223500        2Story         7.0          5.0     2001.0          2002
140000        2Story         7.0          5.0     1915.0          1970
143000        1.5Fin         5.0          5.0     1993.0          1995
307000        1Story         8.0          5.0     2004.0          2005
200000        2Story         7.0          6.0     1973.0          1973
129900        1.5Fin         5.5          5.0     1931.0          1950
118000        1Story         5.0          6.0     1939.0          1950
345000        2Story         9.0          5.0     2005.0          2006

           GarageCars  Overall
SalePrice
208500              2     6.00
181500              2     7.00
223500              2     6.00
140000              3     6.00
143000              2     5.00
307000              2     6.50
200000              2     6.50
129900              2     5.25
118000              1     5.50
345000              3     7.00

[10 rows x 21 columns]

b. Show the summary of the dataframe

In [130]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
count,99.000000,99.000000,85.000000,95.000000,94.000000,95.000000,92.000000,99.000000,99.000000,99.000000
mean,50.000000,52.323232,71.341176,10060.263158,5.957447,5.473684,1971.315217,1984.171717,1.767677,174273.898990
std,28.722813,42.638209,21.210146,5232.546799,1.516326,0.965821,29.771263,20.921642,0.739943,72461.117262
min,1.000000,20.000000,21.000000,1596.000000,3.000000,2.000000,1910.000000,1950.000000,0.000000,40000.000000
25%,25.500000,20.000000,60.000000,7579.500000,5.000000,5.000000,1954.750000,1965.000000,1.000000,129500.000000
50%,50.000000,45.000000,70.000000,9591.000000,6.000000,5.000000,1971.000000,1995.000000,2.000000,154000.000000
75%,74.500000,60.000000,84.000000,11220.500000,7.000000,6.000000,1999.500000,2003.500000,2.000000,208000.000000
max,99.000000,190.000000,122.000000,50271.000000,10.000000,8.000000,2009.000000,2009.000000,3.000000,438780.000000

c. Count the number and percentage of missing data in each column and the entire dataset

In [131]:
nan_counts = df.isna().sum()
nan_percent = nan_counts / len(df) * 100

# Missing data for each columns
nan_table_columns = pd.DataFrame({
    'Missing counts': nan_counts,
    'Missing percent (%)': nan_percent.round(2)
})

print("Missing table for each column:")
nan_table_columns

Missing table for each column:

              Missing counts  Missing percent (%)
Id                         0                 0.00
MSSubClass                 0                 0.00
MSZoning                   0                 0.00
LotFrontage               14                14.14
LotArea                    4                 4.04
Street                     0                 0.00
Alley                     93                93.94
LotShape                   0                 0.00
LandContour                0                 0.00
Utilities                  0                 0.00
LotConfig                  0                 0.00
Neighborhood               0                 0.00
BldgType                   0                 0.00
HouseStyle                 4                 4.04
OverallQual                5                 5.05
OverallCond                4                 4.04
YearBuilt                  7                 7.07
YearRemodAdd               0                 0.00
GarageCars                 0                 0.00
SalePrice                  0                 0.00

In [132]:
# Missing data Entire Dataframe
nan_count_df = nan_counts.sum()
df_size = df.size
nan_percent_df = (nan_count_df / df_size) * 100

nan_table_df = pd.DataFrame({
    'Missing counts': [nan_count_df],
    'Missing percent (%)': [nan_percent_df.round(2)]
})

print("Missing table for entire DataFrame:")
nan_table_df

Missing table for entire DataFrame:

   Missing counts  Missing percent (%)
0             131                 6.62

d. Randomly drop 25% of the rows that have missing data. Hint: use any() and numpy.random.choice()

In [133]:
import numpy as np

missing_rows = df[df.isna().any(axis=1)].index

n_drop = int(0.25 * len(missing_rows))

drop_indices = np.random.choice(missing_rows, size=n_drop, replace=False)

df.drop(drop_indices, axis=0, inplace=True)

print(f"Số hàng đã xóa: {n_drop}")
print(df.shape)

Số hàng đã xóa: 23
(76, 20)

e. Fill in the missing data with *median* (if the column data type is numeric) or *mode* (if the column data type is not numeric)

In [134]:
#df colums type
df.dtypes

Id                int64
MSSubClass        int64
MSZoning         object
LotFrontage     float64
LotArea         float64
Street           object
Alley            object
LotShape         object
LandContour      object
Utilities        object
LotConfig        object
Neighborhood     object
BldgType         object
HouseStyle       object
OverallQual     float64
OverallCond     float64
YearBuilt       float64
YearRemodAdd      int64
GarageCars        int64
SalePrice         int64
dtype: object

In [135]:
fill_values = {}
for col in df.columns:
    if np.issubdtype(df[col].dtypes, np.number):
        fill_values[col] = df[col].median()
    else:
        fill_values[col] = df[col].mode()[0]

df.fillna(fill_values, inplace=True)
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
0,1,60,RL,65.0,8450.0,Pave,Grvl,Reg,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2003.0,2003,2,208500
1,2,20,RL,80.0,9600.0,Pave,Grvl,Reg,Lvl,AllPub,"""""",Veenker,1Fam,1Story,6.0,8.0,1976.0,1976,2,181500
2,3,60,RL,68.0,11250.0,Pave,Grvl,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2001.0,2002,2,223500
3,4,70,RL,60.0,9550.0,Pave,Grvl,IR1,Lvl,AllPub,Corner,Crawfor,1Fam,2Story,7.0,5.0,1915.0,1970,3,140000
5,6,50,RL,85.0,9268.5,Pave,Grvl,IR1,Lvl,AllPub,Inside,Mitchel,1Fam,1.5Fin,5.0,5.0,1993.0,1995,2,143000
6,7,20,RL,75.0,10084.0,Pave,Grvl,Reg,Lvl,AllPub,Inside,Somerst,1Fam,1Story,8.0,5.0,2004.0,2005,2,307000
7,8,60,RL,69.0,10382.0,Pave,Grvl,IR1,Lvl,AllPub,"""""",NWAmes,1Fam,2Story,7.0,6.0,1973.0,1973,2,200000
8,9,50,RM,51.0,6120.0,Pave,Grvl,Reg,Lvl,AllPub,Inside,OldTown,1Fam,1.5Fin,5.5,5.0,1931.0,1950,2,129900
9,10,190,RL,50.0,7420.0,Pave,Grvl,Reg,Lvl,AllPub,Corner,BrkSide,2fmCon,1Story,5.0,6.0,1939.0,1950,1,118000
11,12,60,RL,85.0,11924.0,Pave,Grvl,IR1,Lvl,AllPub,Inside,NridgHt,1Fam,2Story,9.0,5.0,2005.0,2006,3,345000

f. Show the summary of update dataframe

In [136]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,48.473684,53.157895,71.565789,10045.842105,5.907895,5.513158,1971.710526,1984.421053,1.776316,173706.394737
std,28.718623,44.217961,19.546413,5561.764789,1.457648,0.930855,29.411932,20.562272,0.704248,68589.763968
min,1.000000,20.000000,24.000000,2645.000000,3.000000,3.000000,1910.000000,1950.000000,0.000000,40000.000000
25%,25.750000,20.000000,60.000000,7532.250000,5.000000,5.000000,1957.750000,1965.000000,1.000000,129900.000000
50%,45.500000,37.500000,69.000000,9268.500000,5.500000,5.000000,1973.000000,1994.000000,2.000000,156000.000000
75%,72.250000,62.500000,80.000000,10906.500000,7.000000,6.000000,1999.000000,2003.000000,2.000000,207750.000000
max,99.000000,190.000000,122.000000,50271.000000,9.000000,8.000000,2009.000000,2009.000000,3.000000,385000.000000

g. Extract the row with max SalePrice and the row with min SalePrice

In [137]:
df["SalePrice"].sort_values(ascending=True)

30     40000
29     68500
39     82000
98     83000
17     90000
       ...
35    309000
45    319900
20    325300
11    345000
53    385000
Name: SalePrice, Length: 76, dtype: int64

In [138]:
#row with min SalePrice
df.sort_values(by="SalePrice", ascending=True).head(1)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
30,31,70,C (all),50.0,8500.0,Pave,Pave,Reg,Lvl,AllPub,Inside,IDOTRR,1Fam,2Story,4.0,4.0,1920.0,1950,1,40000

In [139]:
#row with max SalePrice
df.sort_values(by="SalePrice", ascending=False).head(1)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
53,54,20,RL,68.0,50271.0,Pave,Grvl,IR1,Low,AllPub,Inside,Veenker,1Fam,1Story,9.0,5.0,1981.0,1987,3,385000

h. Insert a new column called Overall, which is the average of OverallQual and OverallCond

In [140]:
df["Overall"] = df[["OverallQual", "OverallCond"]].mean(axis=1)

df["Overall"]

0     6.0
1     7.0
2     6.0
3     6.0
5     5.0
     ...
93    6.0
94    5.5
95    5.5
96    6.0
98    5.0
Name: Overall, Length: 76, dtype: float64

i. Update the dataframe with SalePrice used index and ID becomes a new column

In [141]:
df = df.reset_index().rename(columns={"index": "Id"}).set_index("SalePrice")

df.head()

,Id,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,Overall
SalePrice,,,,,,,,,,,,,,,,,,,,,
208500,0,1,60,RL,65.0,8450.0,Pave,Grvl,Reg,Lvl,...,Inside,CollgCr,1Fam,2Story,7.0,5.0,2003.0,2003,2,6.0
181500,1,2,20,RL,80.0,9600.0,Pave,Grvl,Reg,Lvl,...,"""""",Veenker,1Fam,1Story,6.0,8.0,1976.0,1976,2,7.0
223500,2,3,60,RL,68.0,11250.0,Pave,Grvl,IR1,Lvl,...,Inside,CollgCr,1Fam,2Story,7.0,5.0,2001.0,2002,2,6.0
140000,3,4,70,RL,60.0,9550.0,Pave,Grvl,IR1,Lvl,...,Corner,Crawfor,1Fam,2Story,7.0,5.0,1915.0,1970,3,6.0
143000,5,6,50,RL,85.0,9268.5,Pave,Grvl,IR1,Lvl,...,Inside,Mitchel,1Fam,1.5Fin,5.0,5.0,1993.0,1995,2,5.0